"""Static knowledge base: skill taxonomy, job roles, learning resources and interview questions."""

SKILL_ALIASES: dict[str, str] = {
    "js": "javascript",
    "reactjs": "react",
    "react.js": "react",
    "nodejs": "node.js",
    "node": "node.js",
    "postgres": "postgresql",
    "ml": "machine learning",
    "dl": "deep learning",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "tf": "tensorflow",
    "sklearn": "scikit-learn",
    "scikit learn": "scikit-learn",
    "ci/cd": "cicd",
    "amazon web services": "aws",
    "gcp": "google cloud",
    "k8s": "kubernetes",
    "py": "python",
    "ts": "typescript",
    "html5": "html",
    "css3": "css",
    "restful apis": "rest api",
    "rest apis": "rest api",
    "restful": "rest api",
}

KNOWN_SKILLS: set[str] = {
    "python", "java", "c", "c++", "c#", "javascript", "typescript", "go", "rust",
    "html", "css", "react", "angular", "vue", "next.js", "tailwind",
    "node.js", "express", "django", "flask", "fastapi", "spring boot",
    "sql", "mysql", "postgresql", "mongodb", "redis", "sqlite",
    "machine learning", "deep learning", "natural language processing",
    "computer vision", "tensorflow", "pytorch", "scikit-learn", "pandas",
    "numpy", "matplotlib", "data analysis", "data visualization", "statistics",
    "power bi", "tableau", "excel",
    "aws", "azure", "google cloud", "docker", "kubernetes", "cicd", "linux",
    "git", "github", "terraform",
    "rest api", "graphql", "microservices", "system design",
    "data structures", "algorithms", "oops", "dbms", "operating systems",
    "computer networks", "figma", "ui/ux", "agile", "jira",
    "communication", "leadership", "problem solving", "teamwork",
    "kotlin", "swift", "flutter", "react native", "android", "ios",
    "cybersecurity", "penetration testing", "networking", "blockchain",
    "solidity", "prompt engineering", "llm", "langchain", "generative ai",
}

JOB_ROLES: dict[str, dict] = {
    "frontend developer": {
        "title": "Frontend Developer",
        "core_skills": ["html", "css", "javascript", "react", "git"],
        "advanced_skills": ["typescript", "next.js", "tailwind", "rest api", "data structures"],
        "description": "Builds user interfaces and web experiences using modern frameworks.",
        "avg_salary_lpa": "4-12 LPA",
        "demand": "High",
    },
    "backend developer": {
        "title": "Backend Developer",
        "core_skills": ["python", "sql", "rest api", "git", "data structures"],
        "advanced_skills": ["django", "fastapi", "postgresql", "redis", "docker", "microservices"],
        "description": "Designs and builds server-side logic, APIs and databases.",
        "avg_salary_lpa": "5-15 LPA",
        "demand": "High",
    },
    "full stack developer": {
        "title": "Full Stack Developer",
        "core_skills": ["html", "css", "javascript", "react", "node.js", "sql", "git"],
        "advanced_skills": ["typescript", "mongodb", "docker", "rest api", "system design"],
        "description": "Works across frontend and backend to deliver complete products.",
        "avg_salary_lpa": "5-16 LPA",
        "demand": "Very High",
    },
    "data scientist": {
        "title": "Data Scientist",
        "core_skills": ["python", "statistics", "pandas", "numpy", "machine learning", "sql"],
        "advanced_skills": ["deep learning", "tensorflow", "pytorch", "natural language processing", "data visualization"],
        "description": "Extracts insights from data and builds predictive models.",
        "avg_salary_lpa": "6-20 LPA",
        "demand": "Very High",
    },
    "data analyst": {
        "title": "Data Analyst",
        "core_skills": ["excel", "sql", "python", "data analysis", "data visualization"],
        "advanced_skills": ["power bi", "tableau", "statistics", "pandas"],
        "description": "Analyzes business data and creates dashboards and reports.",
        "avg_salary_lpa": "4-10 LPA",
        "demand": "High",
    },
    "machine learning engineer": {
        "title": "Machine Learning Engineer",
        "core_skills": ["python", "machine learning", "scikit-learn", "pandas", "sql", "git"],
        "advanced_skills": ["deep learning", "tensorflow", "pytorch", "docker", "aws", "llm"],
        "description": "Builds, deploys and maintains ML systems in production.",
        "avg_salary_lpa": "8-25 LPA",
        "demand": "Very High",
    },
    "ai engineer": {
        "title": "AI Engineer (GenAI)",
        "core_skills": ["python", "machine learning", "llm", "prompt engineering", "rest api"],
        "advanced_skills": ["langchain", "generative ai", "natural language processing", "docker", "aws"],
        "description": "Builds applications powered by large language models and generative AI.",
        "avg_salary_lpa": "10-30 LPA",
        "demand": "Very High",
    },
    "devops engineer": {
        "title": "DevOps Engineer",
        "core_skills": ["linux", "git", "docker", "cicd", "aws"],
        "advanced_skills": ["kubernetes", "terraform", "python", "networking", "azure"],
        "description": "Automates infrastructure, deployments and reliability of systems.",
        "avg_salary_lpa": "6-18 LPA",
        "demand": "High",
    },
    "android developer": {
        "title": "Android Developer",
        "core_skills": ["kotlin", "java", "android", "git", "rest api"],
        "advanced_skills": ["flutter", "sql", "system design"],
        "description": "Builds native and cross-platform Android applications.",
        "avg_salary_lpa": "4-12 LPA",
        "demand": "Medium",
    },
    "cybersecurity analyst": {
        "title": "Cybersecurity Analyst",
        "core_skills": ["networking", "linux", "cybersecurity", "operating systems"],
        "advanced_skills": ["penetration testing", "python", "cicd"],
        "description": "Protects systems and networks from security threats.",
        "avg_salary_lpa": "5-15 LPA",
        "demand": "High",
    },
}

LEARNING_RESOURCES: dict[str, dict] = {
    "python": {"resource": "Python for Everybody (Coursera) / CS50P", "weeks": 4},
    "javascript": {"resource": "The Odin Project - JavaScript / javascript.info", "weeks": 4},
    "typescript": {"resource": "TypeScript Handbook + Execute Program", "weeks": 2},
    "html": {"resource": "MDN Web Docs - HTML", "weeks": 1},
    "css": {"resource": "MDN Web Docs - CSS + CSS Grid Garden", "weeks": 2},
    "react": {"resource": "react.dev official tutorial + build 3 projects", "weeks": 4},
    "next.js": {"resource": "Next.js Learn (official)", "weeks": 2},
    "tailwind": {"resource": "Tailwind CSS docs + rebuild a UI", "weeks": 1},
    "node.js": {"resource": "Node.js official guide + Express course", "weeks": 3},
    "express": {"resource": "Express docs + REST API project", "weeks": 2},
    "django": {"resource": "Django official polls tutorial + a CRUD app", "weeks": 3},
    "fastapi": {"resource": "FastAPI official tutorial", "weeks": 2},
    "sql": {"resource": "SQLBolt + Mode SQL tutorial", "weeks": 2},
    "mysql": {"resource": "MySQL docs + practice on LeetCode DB", "weeks": 2},
    "postgresql": {"resource": "PostgreSQL Tutorial (postgresqltutorial.com)", "weeks": 2},
    "mongodb": {"resource": "MongoDB University M001", "weeks": 2},
    "redis": {"resource": "Redis University RU101", "weeks": 1},
    "machine learning": {"resource": "Andrew Ng ML Specialization (Coursera)", "weeks": 8},
    "deep learning": {"resource": "DeepLearning.AI Deep Learning Specialization", "weeks": 8},
    "natural language processing": {"resource": "Hugging Face NLP Course", "weeks": 4},
    "computer vision": {"resource": "fast.ai + OpenCV tutorials", "weeks": 4},
    "tensorflow": {"resource": "TensorFlow Developer Certificate path", "weeks": 4},
    "pytorch": {"resource": "PyTorch official 60-min blitz + tutorials", "weeks": 3},
    "scikit-learn": {"resource": "scikit-learn user guide + Kaggle micro-courses", "weeks": 2},
    "pandas": {"resource": "Kaggle Pandas course + practice datasets", "weeks": 2},
    "numpy": {"resource": "NumPy official quickstart", "weeks": 1},
    "statistics": {"resource": "Khan Academy Statistics & Probability", "weeks": 4},
    "data analysis": {"resource": "Google Data Analytics Certificate", "weeks": 6},
    "data visualization": {"resource": "Storytelling with Data + Matplotlib/Seaborn", "weeks": 2},
    "power bi": {"resource": "Microsoft Learn - Power BI", "weeks": 2},
    "tableau": {"resource": "Tableau Public free training videos", "weeks": 2},
    "excel": {"resource": "Excel Skills for Business (Coursera)", "weeks": 2},
    "aws": {"resource": "AWS Cloud Practitioner Essentials", "weeks": 3},
    "azure": {"resource": "Microsoft Learn AZ-900 path", "weeks": 3},
    "google cloud": {"resource": "Google Cloud Skills Boost", "weeks": 3},
    "docker": {"resource": "Docker official get-started + dockerize a project", "weeks": 2},
    "kubernetes": {"resource": "Kubernetes docs + KodeKloud CKA basics", "weeks": 4},
    "cicd": {"resource": "GitHub Actions docs + set up a pipeline", "weeks": 1},
    "linux": {"resource": "Linux Journey + OverTheWire Bandit", "weeks": 3},
    "git": {"resource": "Pro Git book (ch 1-3) + learngitbranching.js.org", "weeks": 1},
    "terraform": {"resource": "HashiCorp Learn - Terraform", "weeks": 2},
    "rest api": {"resource": "Build & document a REST API (any stack)", "weeks": 2},
    "graphql": {"resource": "graphql.org tutorial + Apollo docs", "weeks": 2},
    "microservices": {"resource": "microservices.io patterns + a demo project", "weeks": 3},
    "system design": {"resource": "System Design Primer (GitHub)", "weeks": 6},
    "data structures": {"resource": "NeetCode 150 / Striver A2Z DSA sheet", "weeks": 8},
    "algorithms": {"resource": "NeetCode 150 / Striver A2Z DSA sheet", "weeks": 8},
    "kotlin": {"resource": "Kotlin official docs + Android Basics", "weeks": 3},
    "android": {"resource": "Android Basics with Compose (Google)", "weeks": 6},
    "flutter": {"resource": "Flutter codelabs (official)", "weeks": 4},
    "networking": {"resource": "Computer Networking: Top-Down Approach + labs", "weeks": 4},
    "cybersecurity": {"resource": "TryHackMe Pre-Security path", "weeks": 4},
    "penetration testing": {"resource": "TryHackMe Jr Penetration Tester path", "weeks": 6},
    "llm": {"resource": "DeepLearning.AI short courses on LLMs", "weeks": 2},
    "langchain": {"resource": "LangChain docs + build a RAG app", "weeks": 2},
    "prompt engineering": {"resource": "DeepLearning.AI Prompt Engineering course", "weeks": 1},
    "generative ai": {"resource": "Google Generative AI learning path", "weeks": 2},
}

INTERVIEW_QUESTIONS: dict[str, list[dict]] = {
    "hr": [
        {"question": "Tell me about yourself and your career goals.",
         "keywords": ["experience", "project", "goal", "learn", "skill", "passion"]},
        {"question": "What is your greatest strength and how have you used it?",
         "keywords": ["strength", "example", "team", "result", "project"]},
        {"question": "Describe a challenge you faced and how you overcame it.",
         "keywords": ["challenge", "problem", "solution", "learn", "result"]},
        {"question": "Why do you want this role, and where do you see yourself in 3 years?",
         "keywords": ["growth", "role", "company", "learn", "goal", "contribute"]},
    ],
    "technical": [
        {"question": "Explain a project from your resume: architecture, your role, and key decisions.",
         "keywords": ["architecture", "database", "api", "design", "decision", "built", "implemented"]},
        {"question": "How do you debug a production issue you have never seen before?",
         "keywords": ["logs", "reproduce", "isolate", "monitor", "root cause", "test"]},
        {"question": "Explain the difference between SQL and NoSQL databases and when to use each.",
         "keywords": ["schema", "scale", "relational", "document", "transaction", "consistency"]},
        {"question": "What happens when you type a URL in the browser and press Enter?",
         "keywords": ["dns", "http", "tcp", "server", "request", "response", "render"]},
    ],
    "frontend developer": [
        {"question": "Explain the virtual DOM and how React decides what to re-render.",
         "keywords": ["virtual dom", "diff", "reconciliation", "state", "props", "render"]},
        {"question": "How would you optimize the performance of a slow web page?",
         "keywords": ["lazy", "bundle", "cache", "image", "memo", "lighthouse", "code splitting"]},
    ],
    "backend developer": [
        {"question": "How do you design a REST API for a bookstore? Walk through endpoints and status codes.",
         "keywords": ["get", "post", "put", "delete", "status", "resource", "endpoint"]},
        {"question": "How would you handle 10x traffic growth on your API?",
         "keywords": ["cache", "scale", "load balancer", "queue", "database", "index", "horizontal"]},
    ],
    "data scientist": [
        {"question": "Explain the bias-variance tradeoff with an example.",
         "keywords": ["overfitting", "underfitting", "bias", "variance", "complexity", "regularization"]},
        {"question": "How do you handle missing data and outliers in a dataset?",
         "keywords": ["imputation", "mean", "median", "drop", "outlier", "iqr", "distribution"]},
    ],
    "machine learning engineer": [
        {"question": "How would you deploy and monitor an ML model in production?",
         "keywords": ["docker", "api", "monitor", "drift", "version", "pipeline", "retrain"]},
        {"question": "Explain how you would evaluate a classification model on imbalanced data.",
         "keywords": ["precision", "recall", "f1", "auc", "imbalanced", "confusion matrix"]},
    ],
    "devops engineer": [
        {"question": "Design a CI/CD pipeline for a microservices application.",
         "keywords": ["build", "test", "deploy", "docker", "pipeline", "rollback", "stage"]},
        {"question": "A server is running out of disk space at 3 AM. Walk through your response.",
         "keywords": ["df", "logs", "alert", "clean", "monitor", "root cause", "automate"]},
    ],
}
